version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile_db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5121508
      POSTGRES_DB: catering_notif_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migration:
    build:
      context: .
      dockerfile: docker/Dockerfile_migration
    depends_on:
      - db
    environment:
      DATABASE_URL: "host=db user=postgres password=5121508 dbname=catering_notif_db port=5432 sslmode=disable" 

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  notif_service:
    build:
      context: .
      dockerfile: docker/Dockerfile_service
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: "host=db user=postgres password=5121508 dbname=catering_notif_db port=5432 sslmode=disable" 
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
    ports:
      - "8082:8082"



volumes:
  pgdata: