// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: notification_service.proto

package notification_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_notification_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ResetStruct
type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ResetCode     int32                  `protobuf:"varint,2,opt,name=resetCode,proto3" json:"resetCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_notification_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{1}
}

func (x *ResetRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetRequest) GetResetCode() int32 {
	if x != nil {
		return x.ResetCode
	}
	return 0
}

// DeliverStruct
type DeliverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Product       string                 `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Item          string                 `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRequest) Reset() {
	*x = DeliverRequest{}
	mi := &file_notification_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRequest) ProtoMessage() {}

func (x *DeliverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRequest.ProtoReflect.Descriptor instead.
func (*DeliverRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeliverRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DeliverRequest) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *DeliverRequest) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

// SellStruct
type SellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Product       string                 `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Fee           float64                `protobuf:"fixed64,4,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellRequest) Reset() {
	*x = SellRequest{}
	mi := &file_notification_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellRequest) ProtoMessage() {}

func (x *SellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellRequest.ProtoReflect.Descriptor instead.
func (*SellRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{3}
}

func (x *SellRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SellRequest) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *SellRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SellRequest) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

var File_notification_service_proto protoreflect.FileDescriptor

const file_notification_service_proto_rawDesc = "" +
	"\n" +
	"\x1anotification_service.proto\x12\x05notif\"8\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\fResetRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1c\n" +
	"\tresetCode\x18\x02 \x01(\x05R\tresetCode\"T\n" +
	"\x0eDeliverRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x12\n" +
	"\x04item\x18\x03 \x01(\tR\x04item\"e\n" +
	"\vSellRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x10\n" +
	"\x03fee\x18\x04 \x01(\x01R\x03fee2\xb3\x01\n" +
	"\x13NotificationService\x122\n" +
	"\n" +
	"ResetNotif\x12\x13.notif.ResetRequest\x1a\x0f.notif.Response\x126\n" +
	"\fDeliverNotif\x12\x15.notif.DeliverRequest\x1a\x0f.notif.Response\x120\n" +
	"\tSellNotif\x12\x12.notif.SellRequest\x1a\x0f.notif.ResponseB\x17Z\x15/notification_serviceb\x06proto3"

var (
	file_notification_service_proto_rawDescOnce sync.Once
	file_notification_service_proto_rawDescData []byte
)

func file_notification_service_proto_rawDescGZIP() []byte {
	file_notification_service_proto_rawDescOnce.Do(func() {
		file_notification_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_service_proto_rawDesc), len(file_notification_service_proto_rawDesc)))
	})
	return file_notification_service_proto_rawDescData
}

var file_notification_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_notification_service_proto_goTypes = []any{
	(*Response)(nil),       // 0: notif.Response
	(*ResetRequest)(nil),   // 1: notif.ResetRequest
	(*DeliverRequest)(nil), // 2: notif.DeliverRequest
	(*SellRequest)(nil),    // 3: notif.SellRequest
}
var file_notification_service_proto_depIdxs = []int32{
	1, // 0: notif.NotificationService.ResetNotif:input_type -> notif.ResetRequest
	2, // 1: notif.NotificationService.DeliverNotif:input_type -> notif.DeliverRequest
	3, // 2: notif.NotificationService.SellNotif:input_type -> notif.SellRequest
	0, // 3: notif.NotificationService.ResetNotif:output_type -> notif.Response
	0, // 4: notif.NotificationService.DeliverNotif:output_type -> notif.Response
	0, // 5: notif.NotificationService.SellNotif:output_type -> notif.Response
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_service_proto_init() }
func file_notification_service_proto_init() {
	if File_notification_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_service_proto_rawDesc), len(file_notification_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_service_proto_goTypes,
		DependencyIndexes: file_notification_service_proto_depIdxs,
		MessageInfos:      file_notification_service_proto_msgTypes,
	}.Build()
	File_notification_service_proto = out.File
	file_notification_service_proto_goTypes = nil
	file_notification_service_proto_depIdxs = nil
}
